//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat16
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние.
    /// </summary>
    // *** Start programmer edit section *** (Состояние CustomAttributes)

    // *** End programmer edit section *** (Состояние CustomAttributes)
    public enum Состояние
    {
        
        // *** Start programmer edit section *** (Состояние.Оформлен CustomAttributes)

        // *** End programmer edit section *** (Состояние.Оформлен CustomAttributes)
        [Caption("Оформлен")]
        Оформлен,
        
        // *** Start programmer edit section *** (Состояние.РазгрузкаВПунктеВыдаче CustomAttributes)

        // *** End programmer edit section *** (Состояние.РазгрузкаВПунктеВыдаче CustomAttributes)
        [Caption("Разгрузка в пункте выдаче")]
        РазгрузкаВПунктеВыдаче,
        
        // *** Start programmer edit section *** (Состояние.СобранНаСкладе CustomAttributes)

        // *** End programmer edit section *** (Состояние.СобранНаСкладе CustomAttributes)
        [Caption("Собран на складе")]
        СобранНаСкладе,
        
        // *** Start programmer edit section *** (Состояние.ОтправленНаСборку CustomAttributes)

        // *** End programmer edit section *** (Состояние.ОтправленНаСборку CustomAttributes)
        [Caption("Отправлен на сборку")]
        ОтправленНаСборку,
        
        // *** Start programmer edit section *** (Состояние.ГотовКВыдачи CustomAttributes)

        // *** End programmer edit section *** (Состояние.ГотовКВыдачи CustomAttributes)
        [Caption("Готов к выдачи")]
        ГотовКВыдачи,
        
        // *** Start programmer edit section *** (Состояние.ВПути CustomAttributes)

        // *** End programmer edit section *** (Состояние.ВПути CustomAttributes)
        [Caption("В пути")]
        ВПути,
    }
}
